### PR TITLE
remove system file inst

### LINKED ISSUE #81: [Bug]: Files in `inst` are installed at top-level.
### What happened?

Running `devtools::document(roclets = c('rd', 'collate', 'namespace'))` on  ghcr.io/insightsengineering/rstudio_4.2.1_bioc_3.15:latest (https://github.com/insightsengineering/ci-images/pkgs/container/rstudio_4.2.1_bioc_3.15) will throw exception:
```
Error in `system.file()` at teal.data/R/utils.R:79:2:
! Paths can't start with `inst`
ℹ Files in `inst` are installed at top-level.

```

### sessionInfo()

```R
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1
```

### Relevant log output

```R
ℹ Updating teal.data documentation
ℹ Loading teal.data
Error in `system.file()` at teal.data/R/utils.R:79:2:
! Paths can't start with `inst`
ℹ Files in `inst` are installed at top-level.
Backtrace:
     ▆
  1. ├─base::suppressPackageStartupMessages(...)
  2. │ └─base::withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
  3. └─devtools::document(roclets = c("rd", "collate", "namespace"))
  4.   └─roxygen2::roxygenise(pkg$path, roclets)
  5.     └─roxygen2 (local) load_code(base_path)
  6.       └─pkgload::load_all(path, helpers = FALSE, attach_testthat = FALSE)
  7.         └─pkgload:::run_pkg_hook(package, "load")
  8.           └─nsenv[[f_name]](dirname(ns_path), package)
  9.             ├─yaml::yaml.load_file(get_package_file("teal.data", "cdisc_datasets/cdisc_datasets.yaml")) at teal.data/R/zzz.R:4:2
 10.             └─teal.data:::get_package_file("teal.data", "cdisc_datasets/cdisc_datasets.yaml")
 11.               └─pkgload (local) system.file("inst", file_name, package = pkg) at teal.data/R/utils.R:79:2
 12.                 └─cli::cli_abort(c("Paths can't start with `inst`", i = "Files in `inst` are installed at top-level."))
 13.                   └─rlang::abort(message, ..., call = call, use_cli_format = TRUE)
Execution halted

Exited with status 1.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by nikolas-burkoff**
Closes #81 

image

This function is only used in `.onLoad`

FYI @arkadiuszbeer

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -76,11 +76,11 @@ get_package_file <- function(pkg = NULL, file_name = NULL) {
...
   base_file <- system.file(file_name, package = pkg)
-  inst_file <- system.file("inst", file_name, package = pkg)
+  inst_file <- file.path(system.file(package = pkg), file_name)
 
   if (file.exists(base_file)) {
     return(base_file)
-  } else if (file.exists(inst_file)) {
+  } else if (file.exists()) {
     return(inst_file)
   } else {
```
Comment (nikolas-burkoff) [inline R/utils.R:85]: @gogonzo do we actually need inst_file? Or should I remove lines 79 + 83 + 84 ?

Comment (Polkas) [reply R/utils.R:85]: agree, remove them as in the compiled package there is no inst directory.

**Comment by Polkas** [comment]
The base::system.file is overwritten by the pkgdown version:

```
> system.file
function (..., package = "base", lib.loc = NULL, mustWork = FALSE) 
{
    if (!(package %in% dev_packages())) {
        return(base::system.file(..., package = package, lib.loc = lib.loc, 
            mustWork = mustWork))
    }
    if (dots_n(...) && is_string(..1)) {
        if (is_string("inst", ..1) || grepl("^inst/", ..1)) {
            cli::cli_abort(c("Paths can't start with `inst`", 
                i = "Files in `inst` are installed at top-level."))
        }
    }
    pkg_path <- find.package(package)
    files_inst <- file.path(pkg_path, "inst", ...)
    present_inst <- file.exists(files_inst)
    files_top <- file.path(pkg_path, ...)
    present_top <- file.exists(files_top)
    files <- files_top
    files[present_inst] <- files_inst[present_inst]
    files <- files[present_inst | present_top]
    if (length(files) > 0) {
        normalizePath(files, winslash = "/")
    }
    else {
        if (mustWork) {
            cli::cli_abort("Can't find package file.", call = NULL)
        }
        ""
    }
}
<bytecode: 0x1374fa068>
<environment: namespace:pkgload>
```

There two solutions:
-  remove the lines suggested by Nick 
- add base:: prefix to system.file calls

File: R/utils.R [hunk 2]
```diff
@@ -76,7 +76,7 @@ get_package_file <- function(pkg = NULL, file_name = NULL) {
   checkmate::assert_string(pkg)
   checkmate::assert_string(file_name)
   base_file <- system.file(file_name, package = pkg)
-  inst_file <- system.file("inst", file_name, package = pkg)
+  inst_file <- file.path(system.file(package = pkg), file_name)
```
Comment (Polkas) [inline R/utils.R:79]:
```suggestion
```

File: R/utils.R [hunk 3]
```diff
@@ -76,7 +76,7 @@ get_package_file <- function(pkg = NULL, file_name = NULL) {
   checkmate::assert_string(pkg)
   checkmate::assert_string(file_name)
   base_file <- system.file(file_name, package = pkg)
```
Comment (Polkas) [inline R/utils.R:78]:
```suggestion
  base_file <- base::system.file(file_name, package = pkg)
```

**Review by Polkas — APPROVED** [review]
