### PR TITLE
271 fix `assign` function detection for cases with more than 2 arguments

### LINKED ISSUE #271: [Bug]: assign detection failed for `get_code()`
Initially found in https://github.com/insightsengineering/teal.data/pull/263#discussion_r1463370245
Resulted code does not return `assign` function which is wrong.
```r
data <- teal_data() |> eval_code(
  code = '
    x <- 1
    assign("x", 0, envir = environment())
    y <- x
  '
)

identical(
  get_code(data, datanames = "y"),
  paste(
    'x <- 1',
    'assign("x", 0, envir = environment())',
    'y <- x'
  )
)

```

### PR DESCRIPTION
**Pull request by m7pr**
Close #271

### CODE REVIEW

File: R/utils-get_code_dependency.R [hunk 1]
```diff
@@ -205,9 +205,10 @@ extract_occurrence <- function(calls_pd) {
       assign_call <- find_call(call_pd, "assign")
       if (assign_call) {
         # Check if parameters were named.
+        # "','" is for unnamed parameters, where "SYMBOL_SUB" is for named.
         if (any(call_pd$token == "SYMBOL_SUB")) {
-          params <- call_pd[call_pd$token == "SYMBOL_SUB", "text"]
-          pos <- match("x", params, nomatch = length(params) + 1L)
+          params <- call_pd[call_pd$token %in% c("SYMBOL_SUB", "','"), "text"]
+          pos <- match("x", setdiff(params, ","), nomatch = min(which(params == ",")))
```
Comment (chlebowa) [inline R/utils-get_code_dependency.R:211]:
```suggestion
          pos <- match("x", setdiff(params, ","), nomatch = match(",", params, nomatch = return(character(0L)))
```

File: tests/testthat/test-get_code.R [hunk 2]
```diff
@@ -264,6 +264,23 @@ testthat::test_that("@linksto tag indicate affected object if object is assigned
   )
 })
 
+testthat::test_that("get_code works for assign detection no matter how many parametrers were provided in assign", {
+  code = c(
```
Comment (averissimo) [inline tests/testthat/test-get_code.R:268]:
```suggestion
  code <- c(
```

Comment (averissimo) [inline tests/testthat/test-get_code.R:268]:
```suggestion
  code <- c(
```

File: tests/testthat/test-get_code.R [hunk 3]
```diff
@@ -264,6 +264,23 @@ testthat::test_that("@linksto tag indicate affected object if object is assigned
...
+    "x <- 1",
+    "assign(\"x\", 0, envir = environment())",
+    "y <- x"
+  )
+
+  tdata <- teal_data() |> eval_code(code)
```
Comment (averissimo) [inline tests/testthat/test-get_code.R:274]: Should we use `|>`?

The R requirement is "only" 4.0 and it doesn't support the native pipe

I can't find the release notes, but here's a console with R 4.0.5

image

File: R/utils-get_code_dependency.R [hunk 4]
```diff
@@ -205,9 +205,10 @@ extract_occurrence <- function(calls_pd) {
       assign_call <- find_call(call_pd, "assign")
       if (assign_call) {
         # Check if parameters were named.
+        # "','" is for unnamed parameters, where "SYMBOL_SUB" is for named.
         if (any(call_pd$token == "SYMBOL_SUB")) {
```
[the remark this answers is not in the document]
Comment (m7pr) [reply R/utils-get_code_dependency.R:209]: tackled by `return(character(0))` in later `match()` call

**Review by chlebowa — CHANGES_REQUESTED** [review]

File: tests/testthat/test-get_code.R (hunk 3 above)
Comment (chlebowa) [reply tests/testthat/test-get_code.R:274]: You are correct, I will remove pipes in #263

Comment (m7pr) [reply tests/testthat/test-get_code.R:274]: will change to `eval_code(teal_data(), code)`

File: tests/testthat/test-get_code.R [hunk 5]
```diff
@@ -264,6 +264,23 @@ testthat::test_that("@linksto tag indicate affected object if object is assigned
...
 })
 
+testthat::test_that("get_code works for assign detection no matter how many parametrers were provided in assign", {
+  code <- c(
+    "x <- 1",
+    "assign(\"x\", 0, envir = environment())",
+    "y <- x"
+  )
+
+  tdata <- teal_data() |> eval_code(code)
```
Comment (m7pr) [inline tests/testthat/test-get_code.R:274]:
```suggestion
  tdata <- eval_code(teal_data(), code)
```

**Comment by m7pr** [comment]
Hey, explained pos calcualtions in 4806884f8fe6470a68589398f688bcfcac24dfbf

File: R/utils-get_code_dependency.R [hunk 6]
```diff
@@ -205,9 +205,10 @@ extract_occurrence <- function(calls_pd) {
...
-          params <- call_pd[call_pd$token == "SYMBOL_SUB", "text"]
-          pos <- match("x", params, nomatch = length(params) + 1L)
+          params <- call_pd[call_pd$token %in% c("SYMBOL_SUB", "','"), "text"]
```
[the remark this answers is not in the document]
Comment (m7pr) [reply R/utils-get_code_dependency.R:210]: @chlebowa can not do that - this is the name extracted by `getParsedData`. Literally it's the string `"','"` with such usage of quotes : ( unfortunately
image

[the remark this answers is not in the document]
Comment (chlebowa) [reply R/utils-get_code_dependency.R:210]: No worries, I just thought this was an aesthetic choice. If it corresponds to possible input values, it's all right.

**Review by chlebowa — COMMENTED** [review]
Are these tests redundant?
`"get_code works for datanames of length > 1"`
`"get_code with datanames is possible to output the code for multiple objects"`

**Comment by m7pr** [comment]
> Are these tests redundant?
> "get_code works for datanames of length > 1"
> "get_code with datanames is possible to output the code for multiple objects"

Oh yes, I deleted one of them : )

File: tests/testthat/test-get_code.R [hunk 7]
```diff
@@ -264,6 +251,40 @@ testthat::test_that("@linksto tag indicate affected object if object is assigned
...
+    get_code(tdata, datanames = "y"),
+    paste(code, collapse = "\n")
+  )
+
+})
+
+testthat::test_that("get_code detects function usage of assignment operator", {
+  code <- c(
+    "x <- 1",
+    "`<-`(y,x)"
```
Comment (gogonzo) [inline tests/testthat/test-get_code.R:275]: I'm realising that this will be endless struggle with code parsing. We can fill 99.9% of the gaps in `get_code` but there will be always something which can break the parser. Let's keep it experimental and sit down at some point to discuss whether code subsetting has that big value for `teal`.

**Review by chlebowa — APPROVED** [review]
